version: 2
jobs:
  build:

    working_directory: ~/spring-framework-complete

    docker:
      - image: circleci/openjdk:8-jdk-stretch

    steps:

      - checkout

      - restore_cache:
          key: spring-framework-complete-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: spring-framework-complete-{{ checksum "pom.xml" }}

      - run: mvn package

      - store_test_results:
          path: pet-clinic-web/target/surefire-reports

      - store_artifacts:
          path: pet-clinic-web/target/pet-clinic-web-0.0.3-SNAPSHOT.jar

      - run: mvn integration-test